#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Waterbody_Ocean_Parent

#include "Basic.hpp"

#include "FortWaterBodyBP_classes.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Waterbody_Ocean_Parent.Apollo_Waterbody_Ocean_Parent_C
// 0x0020 (0x0350 - 0x0330)
class AApollo_Waterbody_Ocean_Parent_C final : public AFortWaterBodyBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Apollo_Waterbody_Ocean_Parent_C;    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFortSplineWaterAudioComponent*         FortSplineWaterAudio;                              // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FSplineWaterAudioZone>          InsideAudioExclusionZones;                         // 0x0340(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_Apollo_Waterbody_Ocean_Parent(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Waterbody_Ocean_Parent_C">();
	}
	static class AApollo_Waterbody_Ocean_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Waterbody_Ocean_Parent_C>();
	}
};

}

