#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMainMenuLeaveButton

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaMainMenuLeaveButton.AthenaMainMenuLeaveButton_C
// 0x0000 (0x0CF8 - 0x0CF8)
class UAthenaMainMenuLeaveButton_C final : public UFortMainMenuLeaveButton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaMainMenuLeaveButton_C">();
	}
	static class UAthenaMainMenuLeaveButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaMainMenuLeaveButton_C>();
	}
};

}

