#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_Sideways_SplitScreen_P2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Athena_Sideways_SplitScreen_P2.B_Athena_Sideways_SplitScreen_P2_C
// 0x0568 (0x05B0 - 0x0048)
class UB_Athena_Sideways_SplitScreen_P2_C final : public UCameraModifier
{
public:
	TArray<struct FWeightedBlendable>             WeightBlendableStructures;                         // 0x0048(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	uint8                                         Pad_58[0x8];                                       // 0x0058(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPostProcessSettings                   PostProcessSettings;                               // 0x0060(0x0550)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BlueprintModifyPostProcess(float DeltaTime, float* PostProcessBlendWeight, struct FPostProcessSettings* PostProcessSettings_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Athena_Sideways_SplitScreen_P2_C">();
	}
	static class UB_Athena_Sideways_SplitScreen_P2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_Athena_Sideways_SplitScreen_P2_C>();
	}
};

}

