#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_Sideways_SplitScreen_P2

#include "Basic.hpp"

#include "B_Athena_Sideways_SplitScreen_P2_classes.hpp"
#include "B_Athena_Sideways_SplitScreen_P2_parameters.hpp"


namespace SDK
{

// Function B_Athena_Sideways_SplitScreen_P2.B_Athena_Sideways_SplitScreen_P2_C.BlueprintModifyPostProcess
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  PostProcessBlendWeight                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPostProcessSettings*            PostProcessSettings_0                                  (Parm, OutParm)

void UB_Athena_Sideways_SplitScreen_P2_C::BlueprintModifyPostProcess(float DeltaTime, float* PostProcessBlendWeight, struct FPostProcessSettings* PostProcessSettings_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_Sideways_SplitScreen_P2_C", "BlueprintModifyPostProcess");

	Params::B_Athena_Sideways_SplitScreen_P2_C_BlueprintModifyPostProcess Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);

	if (PostProcessBlendWeight != nullptr)
		*PostProcessBlendWeight = Parms.PostProcessBlendWeight;

	if (PostProcessSettings_0 != nullptr)
		*PostProcessSettings_0 = std::move(Parms.PostProcessSettings_0);
}

}

