#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coconut_Island

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Coconut_Island.BP_Coconut_Island_C.SetRockInstances
// 0x0010 (0x0010 - 0x0000)
struct BP_Coconut_Island_C_SetRockInstances final
{
public:
	TArray<class UInstancedStaticMeshComponent*>  K2Node_MakeArray_Array;                            // 0x0000(0x0010)(ReferenceParm, ContainsInstancedReference)
};

}

