#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coconut_Island

#include "Basic.hpp"

#include "BP_Coconut_Island_classes.hpp"
#include "BP_Coconut_Island_parameters.hpp"


namespace SDK
{

// Function BP_Coconut_Island.BP_Coconut_Island_C.SetRockInstances
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Coconut_Island_C::SetRockInstances()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Coconut_Island_C", "SetRockInstances");

	UObject::ProcessEvent(Func, nullptr);
}

}

