#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS18_AboutModal_Decorator

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPS18_AboutModal_Decorator.BPS18_AboutModal_Decorator_C
// 0x0000 (0x0030 - 0x0030)
class UBPS18_AboutModal_Decorator_C final : public URichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPS18_AboutModal_Decorator_C">();
	}
	static class UBPS18_AboutModal_Decorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS18_AboutModal_Decorator_C>();
	}
};

}

