#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeCategoryTab

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeCategoryTab.ChallengeCategoryTab_C
// 0x0000 (0x0C40 - 0x0C40)
class UChallengeCategoryTab_C final : public UChallengeScreenCategoryTab
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChallengeCategoryTab_C">();
	}
	static class UChallengeCategoryTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeCategoryTab_C>();
	}
};

}

