#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EnumOptionDetailsEntry

#include "Basic.hpp"

#include "EnumOptionDetailsEntry_classes.hpp"
#include "EnumOptionDetailsEntry_parameters.hpp"


namespace SDK
{

// Function EnumOptionDetailsEntry.EnumOptionDetailsEntry_C.ExecuteUbergraph_EnumOptionDetailsEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEnumOptionDetailsEntry_C::ExecuteUbergraph_EnumOptionDetailsEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnumOptionDetailsEntry_C", "ExecuteUbergraph_EnumOptionDetailsEntry");

	Params::EnumOptionDetailsEntry_C_ExecuteUbergraph_EnumOptionDetailsEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnumOptionDetailsEntry.EnumOptionDetailsEntry_C.SetupEntry
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    Selected                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UEnumOptionDetailsEntry_C::SetupEntry(const class FText& Text, bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnumOptionDetailsEntry_C", "SetupEntry");

	Params::EnumOptionDetailsEntry_C_SetupEntry Parms{};

	Parms.Text = std::move(Text);
	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}

}

