#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortAIPawnSidewaysComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SidewaysCodeRuntime_structs.hpp"
#include "SidewaysCodeRuntime_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass FortAIPawnSidewaysComponent.FortAIPawnSidewaysComponent_C
// 0x0030 (0x0108 - 0x00D8)
class UFortAIPawnSidewaysComponent_C final : public USidewaysStateComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  T_InsideSideways;                                  // 0x00E0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	TSubclassOf<class UGameplayEffect>            GE_InsideSideways;                                 // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FortAIPawnSidewaysComponent(int32 EntryPoint);
	void HandleSidewaysStateChanged(class ASidewaysPlayspace* NewSidewaysPlayspace, ESidewaysState OldState, ESidewaysState NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortAIPawnSidewaysComponent_C">();
	}
	static class UFortAIPawnSidewaysComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortAIPawnSidewaysComponent_C>();
	}
};

}

