#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HitchhikerRuntime

#include "Basic.hpp"

#include "HitchhikerRuntime_classes.hpp"
#include "HitchhikerRuntime_parameters.hpp"


namespace SDK
{

// Function HitchhikerRuntime.FortHitchhikerComponent_Telemetry.OnDeinfected
// (Final, Native, Public, BlueprintCallable)

void UFortHitchhikerComponent_Telemetry::OnDeinfected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortHitchhikerComponent_Telemetry", "OnDeinfected");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function HitchhikerRuntime.FortHitchhikerComponent_Telemetry.OnInfected
// (Final, Native, Public, BlueprintCallable)

void UFortHitchhikerComponent_Telemetry::OnInfected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortHitchhikerComponent_Telemetry", "OnInfected");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function HitchhikerRuntime.FortHitchhikerComponent_Telemetry.SetWasInfectedAtSpawn
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInfectedAtSpawn                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortHitchhikerComponent_Telemetry::SetWasInfectedAtSpawn(bool bInfectedAtSpawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortHitchhikerComponent_Telemetry", "SetWasInfectedAtSpawn");

	Params::FortHitchhikerComponent_Telemetry_SetWasInfectedAtSpawn Parms{};

	Parms.bInfectedAtSpawn = bInfectedAtSpawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

