#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemPreviewViewport

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemPreviewViewport.ItemPreviewViewport_C
// 0x0008 (0x0268 - 0x0260)
class UItemPreviewViewport_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void ExecuteUbergraph_ItemPreviewViewport(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemPreviewViewport_C">();
	}
	static class UItemPreviewViewport_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemPreviewViewport_C>();
	}
};

}

