#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MoreInfo_Ressources_Button

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MoreInfo_Ressources_Button.MoreInfo_Ressources_Button_C
// 0x0010 (0x0BE0 - 0x0BD0)
class UMoreInfo_Ressources_Button_C final : public UCommonButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Hover;                                             // 0x0BD8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MoreInfo_Ressources_Button(int32 EntryPoint);
	void BP_OnUnhovered();
	void BP_OnHovered();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MoreInfo_Ressources_Button_C">();
	}
	static class UMoreInfo_Ressources_Button_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMoreInfo_Ressources_Button_C>();
	}
};

}

