#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OodleHandlerComponent

#include "Basic.hpp"


namespace SDK
{

// Enum OodleHandlerComponent.EOodleNetResult
// NumValues: 0x0007
enum class EOodleNetResult : uint8
{
	Unknown                                  = 0,
	Success                                  = 1,
	OodleDecodeFailed                        = 2,
	OodleSerializePayloadFail                = 3,
	OodleBadDecompressedLength               = 4,
	OodleNoDictionary                        = 5,
	EOodleNetResult_MAX                      = 6,
};

// Enum OodleHandlerComponent.EOodleEnableMode
// NumValues: 0x0003
enum class EOodleEnableMode : uint8
{
	AlwaysEnabled                            = 0,
	WhenCompressedPacketReceived             = 1,
	EOodleEnableMode_MAX                     = 2,
};

}

