#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Plane_Water_Blueprint

#include "Basic.hpp"

#include "Plane_Water_Blueprint_classes.hpp"
#include "Plane_Water_Blueprint_parameters.hpp"


namespace SDK
{

// Function Plane_Water_Blueprint.Plane_Water_Blueprint_C.ExecuteUbergraph_Plane_Water_Blueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlane_Water_Blueprint_C::ExecuteUbergraph_Plane_Water_Blueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Plane_Water_Blueprint_C", "ExecuteUbergraph_Plane_Water_Blueprint");

	Params::Plane_Water_Blueprint_C_ExecuteUbergraph_Plane_Water_Blueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Plane_Water_Blueprint.Plane_Water_Blueprint_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APlane_Water_Blueprint_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Plane_Water_Blueprint_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

