#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass StatusWidget.StatusWidget_C
// 0x0008 (0x0528 - 0x0520)
class UStatusWidget_C final : public UFortLoginStatus
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0520(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void SetContinueButtonText(const class FText& ContinueText);
	void ExecuteUbergraph_StatusWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StatusWidget_C">();
	}
	static class UStatusWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStatusWidget_C>();
	}
};

}

