#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TabAccountOptions_New

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TabAccountOptions_New.TabAccountOptions_New_C
// 0x0008 (0x0398 - 0x0390)
class UTabAccountOptions_New_C final : public UFortTabAccountOptions_TempNew
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TabAccountOptions_New(int32 EntryPoint);
	void BndEvt__Settings_Panel_K2Node_ComponentBoundEvent_1_OnExecuteNamedActionBP__DelegateSignature(class UFortSetting* Setting, class FName Action);
	void SettingValueChanged(float Value);
	void CenterOnTab();
	void OnComplete_1192BA0E41F4707FF3E3A4A4C72B2024(class UUserWidget* UserWidget);
	void OnComplete_DB10A9674F5CF800B883C79A4229D87C(class UUserWidget* UserWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TabAccountOptions_New_C">();
	}
	static class UTabAccountOptions_New_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabAccountOptions_New_C>();
	}
};

}

