#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamMemberPedestal_ActivatableContainer

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TeamMemberPedestal_ActivatableContainer.TeamMemberPedestal_ActivatableContainer_C
// 0x0008 (0x0350 - 0x0348)
class UTeamMemberPedestal_ActivatableContainer_C final : public UCommonActivatableWidget
{
public:
	class UNamedSlot*                             NamedSlot_Button;                                  // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamMemberPedestal_ActivatableContainer_C">();
	}
	static class UTeamMemberPedestal_ActivatableContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamMemberPedestal_ActivatableContainer_C>();
	}
};

}

