#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TempestRuntime

#include "Basic.hpp"

#include "TempestRuntime_structs.hpp"


namespace SDK::Params
{

// Function TempestRuntime.TempestStateMachineComponent.GetCurrentState
// 0x0001 (0x0001 - 0x0000)
struct TempestStateMachineComponent_GetCurrentState final
{
public:
	ETempestState                                 ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function TempestRuntime.TempestStateMachineComponent.GetCurrentStateCompletionPercentage
// 0x0004 (0x0004 - 0x0000)
struct TempestStateMachineComponent_GetCurrentStateCompletionPercentage final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function TempestRuntime.TempestStateMachineComponent.GetCurrentStateInfo
// 0x000C (0x000C - 0x0000)
struct TempestStateMachineComponent_GetCurrentStateInfo final
{
public:
	struct FTempestStateInfo                      ReturnValue;                                       // 0x0000(0x000C)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

}

