#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WarmupEventCameraShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WarmupEventCameraShake.WarmupEventCameraShake_C
// 0x0000 (0x01B0 - 0x01B0)
class UWarmupEventCameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WarmupEventCameraShake_C">();
	}
	static class UWarmupEventCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWarmupEventCameraShake_C>();
	}
};

}

